<?php

namespace gipfl\RrdTool\Graph\Instruction;

/**
 * man rrdgraph_graph
 * ------------------
 * Draw a line of the specified width onto the graph. width can be a floating
 * point number. If the color is not specified, the drawing is done 'invisibly'.
 * This is useful when stacking something else on top of this line. Also
 * optional is the legend box and string which will be printed in the legend
 * section if specified. The value can be generated by DEF, VDEF, and CDEF.
 *
 * Synopsis
 * --------
 * LINE[width]:value[#color][:[legend][:STACK][:skipscale]
 *     [:dashes[=on_s[,off_s[,on_s,off_s]...]][:dash-offset=offset]]]
 */
class Line extends DefinitionBasedInstruction
{
    use Dashes;
    use SkipScale;
    use Stack;

    /** @var float */
    protected $width = 1;

    /**
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * @param float $width
     * @return $this
     */
    public function setWidth($width)
    {
        $this->width = $width;

        return $this;
    }

    public function render()
    {
        // TODO: Figure out how to comply with this part of the man page:
        // > When you do not specify a color, you cannot specify a legend.
        // > Should you want to use STACK, use the "LINEx:<value>::STACK"
        // > form.

        return sprintf('LINE%.3G:', $this->getWidth())
            . $this->getDefinition()
            . $this->getColor()
            . $this::optionalParameter($this::string($this->getLegend()))
            . $this::optionalNamedBoolean('STACK', $this->isStack())
            . $this::optionalNamedBoolean('skipscale', $this->isSkipScale())
            . $this->renderDashProperties();
    }
}
