<?php

namespace gipfl\RrdTool\Graph\Instruction;

/**
 * man rrdgraph_graph
 * ------------------
 * Depending on the context, either the value component (no suffix, valstrftime
 * or valstrfduration) or the time component (strftime) of a VDEF is printed
 * using format. It is an error to specify a vname generated by a DEF or CDEF.
 *
 * Any text in format is printed literally with one exception: The percent
 * character introduces a formatter string. This string can be: [see manpage]
 *
 * If you PRINT a VDEF value, you can also print the time associated with it by
 * appending the string :strftime to the format. Note that RRDtool uses the
 * strftime function of your OSs C library. This means that the conversion
 * specifier may vary. Check the manual page if you are uncertain. The following
 * is a list of conversion specifiers usually supported across the board.
 *
 * Formatting values interpreted as timestamps with :valstrftime is done
 * likewise.
 *
 * Synopsis
 * --------
 * PRINT:vname:format[:strftime|:valstrftime|:valstrfduration]
 */
class PrintInstruction extends Instruction
{
    protected $tag = 'PRINT';

    /** @var string */
    protected $variableName;

    /** @var string */
    protected $format;

    // TODO: [:strftime|:valstrftime|:valstrfduration]
    public function __construct($vname, $format)
    {
        $this->setVariableName($vname);
        $this->setFormat($format);
    }

    /**
     * @return string
     */
    public function getVariableName()
    {
        return $this->variableName;
    }

    /**
     * @param string $variableName
     * @return $this
     */
    public function setVariableName($variableName)
    {
        $this->variableName = $variableName;
        return $this;
    }

    /**
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * @param string $format
     * @return PrintInstruction
     */
    public function setFormat($format)
    {
        $this->format = $format;
        return $this;
    }

    public function render()
    {
        return $this->tag
            . ':'
            . $this->getVariableName()
            . ':'
            . $this->getFormat()
            ;
    }
}
